# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d190d702c2094d59ce071632aac178b7833665b745c8e149329be3a43d95f5575ed91892fcfedf67714db658be1874e8e6789802c41c3d1fc9eab0ae0323dcee

test:
  secret_key_base: 2ca30cab8e2a49f285f05870ccf7175932a0ea709fe5c66f8751a871d944768288162deb26d361ffbbd421a4e7a97476877abeaaa0afc4c1cde9f63df5cee295

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
